### ISSUE TITLE
Android SDKs Are No Longer Available

### ISSUE THREAD

**Issue by EmirhanSyl** [Estimote/Android-Proximity-SDK#117]
## Basic information

**Estimote SDK version:** com.estimote:proximity-sdk:<ALL_VERSIONS>

**Android devices affected:** Possibly all devices

**Android OS version affected:** Possibly all versions

**Beacon hardware version:** All versions

## Description

The SDK artefacts are no longer available. JCenter shut down 1 year ago and all the SDKs were located there. Only "**proximity-sdk:<1.0.4-1.0.8>**" migrated to Jfrog (Can be found [here](https://estimote.jfrog.io/ui/builds)). However proximity-sdk package is dependent with "com.estimote:scanning-plugin:0.25.4" which is located only JCenter and spring.io. JCenter is shutdown. Spring.io requires creditionals(Can be found [here](https://repo.spring.io/ui/native/plugins-release/com/estimote/indoorsdk/2.0.0/indoorsdk-2.0.0.aar)). As a result, there is no way to reach these SDKs anymore. 

**Steps to reproduce:**

1. Open new project in AndroidStudio with any language(Java or Kotlin)
2. Add SDK as dependency
``` 
dependencies {
    ...
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.estimote:indoorsdk:2.0.0'
} 
```

3.Build project

**Expected behaviour:** Packages imported and build completed.

**Actual behavior:** 
```
Could not find com.estimote:scanning-plugin:0.25.4.
Required by:
    project :app > com.estimote:proximity-sdk:1.0.7
```

## Additional information
Spring.io libraries requires username and password. There is no way to sign up. Host returns 401 status code.

**Comment by MaskedAlkindi** [comment]
Question, so there is no other way to detect estimote beacons anymore, is there any alternative to the proximity sdk to detect proximity of estimote UWB beacons?

**Comment by EmirhanSyl** [comment]
I forgot to update the issue. I solved the problem.

As I mentioned, JCenter is no longer active. However, you can still download old repositories from there. To do that you have to add 'JCenter()' to your repositories in the gradle settings file below to maven(). When you do that, Android Studio gives a warning about this repository being deprecated but it still downloads repository content. The real issue is there is no any single quote about this solution in the original Estimote API description. I mean, it is really easy to solve but challenging to find the issue if you don't know anything about JCenter etc...

**Comment by MaskedAlkindi** [comment]
Hi, thank you so much for the reply, I am a rookie in android development, could you please provide a small example of how to add repos, I would appreciate it a lot and thank you so much for the time, your a hero!

**Comment by EmirhanSyl** [comment]
Sure!

First, you should find the '**settings.gradle**' file in your project.  After that, you should add `jcenter()` to `repositories` section. Here is my settings.gradle file as an example:

`
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        jcenter()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven {
            url "https://estimote.jfrog.io/artifactory/android-proximity-sdk"
        }
    }
}
rootProject.name = "BeaconProximity"
include ':app'
`
