### ISSUE TITLE
How to find the Distance between beacon and phone device 

### ISSUE THREAD

**Issue by rajeshkanna777** [Estimote/Android-Proximity-SDK#13]
## Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** [Paste here the SDK version that you are using (like `0.1.0-alpha.6`)]

**Android devices affected:** [Paste here your Android device model/models that you are having problems with.]

**Android OS version affected:** [Android OS version (ex. `Oreo 8.0.0`)]

**Beacon hardware version:** [Paste here your beacons hardware version (you can check that in Estimote Cloud).] 

## Description

[Description of the issue]

**(Optional) Steps to reproduce:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

## Additional information
```
Add here any logs you want to attach, or any other info, like pictures for example
```
Am using proximity sdk in java code ,i dont know how to find the distance.
In estimote sdk we have RegionUtils.computeAccuracy function but proximity sdk i dont know which method have to call

**Comment by pawelDylag** [comment]
Hey @rajeshkanna777 

1. Why do you need a distance? 
2. `ProximitySDK`allows you to invoke actions on entering/exiting your beacon range. You can specify that when defining your zone:

``` Kotlin
        val beetrootDeskZone = proximityObserver.zoneBuilder()
                ...
                .inCustomRange(/* put your desired distance here */) 
                .withOnEnterAction{ /* do something on entering this distance */ }
                .create()
```
Then in your `/* do something on entering this distance */` you are sure, thet this will be invoked in the distance you provided earlier. 

3. There is no `computeAccuracy` method needed, and in fact there is none like this. 

Regards, 
Paweł
