### ISSUE TITLE
Unable to find java project link for Proximity Sensor.

### ISSUE THREAD

**Issue by VinayTShetty** [Estimote/Android-Proximity-SDK#18]
Hi i am unable to find Java code for Proximity sensor,Everything is in Kotliln. can any one guide me in finding java link  for ProximitySensor

**Comment by wafel82** [comment]
Hi @VinayTShetty 
The Proximity-SDK is written purely in Kotlin.
However - **Kotlin is 100% interoperable with Java**. In other words, you can call Kotlin implementation from  Java code without any issues.
Having said that - there is no point for us to maintain two separate code lines for Java and Kotlin langs.
Please provide exact  java code snippet you are trying to integrate our Kotlin implementation in to.
I hope i'll be able to help you with such integration.

Regards
Wojtek
