### ISSUE TITLE
OnExitAction not being called?

### ISSUE THREAD

**Issue by Zalarox** [Estimote/Android-Proximity-SDK#2]
I'm using the Example application to test the beacons out, and as with the old SDK the onExit event is not being called. 

I'm using Flip To Sleep on my Location Beacon, and if I start the application while the beacon is flipped down, it is not detected. As soon as I flip it back up, it is detected - so I'm sure flip to sleep is working. However, flipping the beacon upside down does not trigger the onExit (even after quite a while).

**Comment by pawelDylag** [comment]
Hey @Zalarox !

Thanks for reporting that - this is a known behaviour, and we plan to improve it in the close future.
This is happening whenever there is a sudden scan cut off (beacon suddenly stopped broadcasting, like flip to sleep) the algorithm won't be able to tell the new proximity of previously seen beacon.

For now you need to test it manually - you can set short distances for your zones for the development process, you can use `.withCustomRange(...)` for that. 

I will let you know when we will release an improvement for this :)

Cheers! 🚀

**Comment by Zalarox** [comment]
Thank you so much for the response! I will go ahead and test using `.withCustomRange()`.
