### ISSUE TITLE
Missing dependency: com.estimote:scanning-plugin:0.14.0

### ISSUE THREAD

**Issue by MBach** [Estimote/Android-Proximity-SDK#23]
## Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** `0.3.0`

## Description

According to your README.md, the latest SDK available for Proximity SDK is 0.3.0. However, I cannot update my project because of the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-estimote-bridge'.
      > Could not resolve all dependencies for configuration ':react-native-estimote-bridge:_debugPublishCopy'.
         > Could not find com.estimote:scanning-plugin:0.14.0.
           Required by:
               Ynovcampus:react-native-estimote-bridge:unspecified > com.estimote:proximity-sdk:0.3.0
```

**Comment by pawelDylag** [comment]
Hey @MBach 

My fault, just added missing dependency to version `0.3.1`. Should be working now :)

Cheers!

**Comment by thanhnvpk01168** [comment]
@pawelDylag , i have a same problem
<img width="1570" alt="Screen Shot 2022-06-17 at 6 38 46 PM" src="https://user-images.githubusercontent.com/58645779/174291249-015a1a3a-0c5b-4565-9a6d-db3da52db487.png">
