### ISSUE TITLE
Access Beacon Identifier

### ISSUE THREAD

**Issue by kanamarhoon** [Estimote/Android-Proximity-SDK#24]
Hello,
I'm working on an android app that uses beacons and need to get the beacon identifier from the proximityObserver.
I get these messages in the log tab:

```
D/ProximityAnalytics: Reporting start monitoring for f9b26cb6ab3bdeea6c2db393c7d1441a
D/ProximitySDK: Sent usage metrics of one id
D/ProximityAnalytics: Reporting ENTER for f9b26cb6ab3bdeea6c2db393c7d1441a
D/ProximityAnalytics: Reporting EXIT for f9b26cb6ab3bdeea6c2db393c7d1441a
```
How/Where can I get/save this identifier?

**Comment by pawelDylag** [comment]
Hey @kanamarhoon 

The question is why do you need those identifiers? Is your use case unable to build on top of attachments? The logs you see are our internal messages throughout the beta stage of our SDK - all of them will be gone since version `1.0.0`.
