### ISSUE TITLE
Why you reply fast on github  but i message on facebook and post in forum and also email the support no reply so i try to post a issue on github 

### ISSUE THREAD

**Issue by jmluansing** [Estimote/Android-Proximity-SDK#26]
## Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** [Paste here the SDK version that you are using (like `0.1.0-alpha.6`)]

**Android devices affected:** [Paste here your Android device model/models that you are having problems with.]

**Android OS version affected:** [Android OS version (ex. `Oreo 8.0.0`)]

**Beacon hardware version:** [Paste here your beacons hardware version (you can check that in Estimote Cloud).] 

## Description

[Description of the issue]

**(Optional) Steps to reproduce:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

## Additional information
```
Add here any logs you want to attach, or any other info, like pictures for example
```

**Comment by pawelDylag** [comment]
Hey @jmluansing 

The Github page is managed by our engineers, but we are focused on writing code and helping with actual issues (something not working etc). The sample apps on our Estimote Cloud are a little bit outdated as far as I know - we will be updating them to Kotlin and Proximity SDK in the near future. For now you have to write your own code, which I really encourage you to do. 

Also, for the sake of clarity, please don't write actual message in the topic of the issue. 

Kind regards, 
Paweł
