### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by MBach** [Estimote/Android-Proximity-SDK#3]
Hi,

You should modify the README.md. 

- [ ] Imports are missing:

    
        import com.estimote.cloud_plugin.common.EstimoteCloudCredentials;
        import com.estimote.proximity_sdk.proximity.ProximityObserver;
        import com.estimote.proximity_sdk.proximity.ProximityObserverFactory;
        import com.estimote.internal_plugins_api.cloud.proximity.ProximityAttachment;
    
        import kotlin.jvm.functions.Function1;

- [x] ProximityRule doesn't exist!
- [x] According to withOnExitAction, it's Function1 and not Function0

        ProximityZone zone1 = proximityObserver.zoneBuilder()
                .forAttachmentKeyAndValue("venue", "office")
                .inFarRange()
                .withOnEnterAction(new Function1<ProximityAttachment, Unit>() {
                    @Override
                    public Unit invoke(ProximityAttachment proximityAttachment) {
                        /* Do something here */
                        return null;
                    }
                })
                .withOnExitAction(new Function1<ProximityAttachment, Unit>() {
                    @Override
                    public Unit invoke(ProximityAttachment proximityAttachment) {
                        /* Do something here */
                        return null;
                    }
                })
                .withOnChangeAction(new Function1<List<? extends ProximityAttachment>, Unit>() {
                    @Override
                    public Unit invoke(List<? extends ProximityAttachment> proximityAttachments) {
                        /* Do something here */
                        return null;
                    }
                })
                .create();

Personnaly, I'm not a big fan of underscores in packages names, but it is allowed, so, whatever.

**Comment by pawelDylag** [comment]
Hey @MBach 

Thank you for pointing out those nasty typos - some samples might have been overlooked while updating API changes after `0.1.0-alpha.5` version. 

1. Imports are unnecessary in code samples - the raw functionality must be in focus, not the secondary things. And unless you are using modern IDE like Android Studio, it will take care of those imports for you (`alt + enter` on mac, for example). 
2. You're right - I updated `ProximityRule` to `ProximityZone` and [added several more fixes](https://github.com/Estimote/Android-Proximity-SDK/commit/d07bbaeb7a620281811b1da791ac02fd616bd795) according to your suggestions.
3. Also fixed -> same as above.

I appreciate your opinion on using underscores in package names. In fact, there is no argumentation against using them (beside pure aesthetics, which is subjective), and it makes long names easier to read - and this is some value to me :)

Let us know about any other ideas that will come to your mind - we're still in `alpha`, but will soon be production ready :)

Regards, 
Paweł

**Comment by MBach** [comment]
About the imports, in fact there's no javadoc yet, and I'm working with react-native. I mostly use VSCode so I had to manually open the jar in my gradle cache to guess what were the right names. Not really a big deal but it might save some time to others I think.

**Comment by pawelDylag** [comment]
@MBach, our SDK has no direct support for React Native for now, so you need to do the stuff manually at the moment. FWe will consider advancing our SDK to be React Native friendly, but honestly, not in the close future.

Good luck with your coding!
