### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by MBach** [Estimote/Android-Proximity-SDK#30]
The link pointing at 'Estimote SDK for Android forum' is dead.

I assume it's now for both iOS and Android: https://forums.estimote.com/c/proximity ?

**Comment by pawelDylag** [comment]
Thanks for pointing that out. Yes, our forums have changed a little bit a few days ago :)
Fixed the dead link in README in https://github.com/Estimote/Android-Proximity-SDK/commit/a3b0600553e409310b6c92370ae302cd39a7d08e
