### ISSUE TITLE
How to get distance value from beacon to device 

### ISSUE THREAD

**Issue by rajeshkanna777** [Estimote/Android-Proximity-SDK#34]
## Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** [Paste here the SDK version that you are using (like `0.1.0-alpha.6`)]

**Android devices affected:** [Paste here your Android device model/models that you are having problems with.]

**Android OS version affected:** [Android OS version (ex. `Oreo 8.0.0`)]

**Beacon hardware version:** [Paste here your beacons hardware version (you can check that in Estimote Cloud).] 

## Description

[Description of the issue]

**(Optional) Steps to reproduce:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

## Additional information
```
Add here any logs you want to attach, or any other info, like pictures for example
```
I want to know distance for each beacon when i pass the Rssi value of beacon .

        BluetoothScanner scanner = new EstimoteBluetoothScannerFactory(MainActivity.this).getSimpleScanner();
        scanner.estimoteConnectivityScan()
                .withLowLatencyPowerMode()
                .withOnPacketFoundAction(new Function1<EstimoteConnectivity, Unit>() {

                    @Override
                    public Unit invoke(EstimoteConnectivity estimoteConnectivity) {
                        Log.i("ProximitySDK", "Found device " + estimoteConnectivity.getDeviceId());
                      
                        return null;
                    }
                }).start();
so in this function i can get each beacon details without distance.

**Comment by pawelDylag** [comment]
Hey @rajeshkanna777 

There is no possibility to get RSSI nor distance from our ProximityObserver. It's impossible to know **exact** distance from the bluetooth signal **due to the nature of radio waves**. We really encourage you to change your mindset, and start thinking in terms of granular "zones", and not the precise distances. 

The RSSI value is indeed available while using low level scanning with `BluetoothScanner`, but it's not available in the `ProximityObserver`.

Regards, 
Paweł

**Comment by rajeshkanna777** [comment]
Hi pawelDylag 
 Then how to find the distance from device to beacon, because i want to find where am located in the floor based on proximity beacon. In previous SDK (Estimote SDK for Android) i can get the distance from beacon to device

**Comment by pawelDylag** [comment]
@rajeshkanna777 use `ProximityObserver` and define zones for you beacons. You can then set the expected distance, and our SDK will notify you actions based on the given parameters (zone key/value and expected distance).  
``` Java
 proximityObserver.zoneBuilder()
        .forAttachmentKeyAndValue("venue", "office")
        .inFarRange()
        .withOnEnterAction(new Function1<ProximityAttachment, Unit>() {
          @Override public Unit invoke(ProximityAttachment proximityAttachment) {
            /* Do something here */
            return null;
          }
        })
        .withOnExitAction(new Function1<ProximityAttachment, Unit>() {
              @Override
              public Unit invoke(ProximityAttachment proximityAttachment) {
                  /* Do something here */
                  return null;
              }
          })
```

**Comment by rajeshkanna777** [comment]
Ya this one we can find entry or exit at whenever i see the beacon ,but i want to keep listerning where am in and which room

**Comment by pawelDylag** [comment]
So you should try using our [Indoor Location SDK](https://github.com/Estimote/Android-Indoor-SDK) for Android. It will deliver you an exact (x,y) coordinates in the given location - you will have to setup beacons in the location and have the location generated in our cloud, but it will work as you needed :)
