### ISSUE TITLE
io.reactivex.exceptions.UndeliverableException: java.lang.Exception: Bluetooth Low Energy scan failed with error code: 2

### ISSUE THREAD

**Issue by JaoBiceps** [Estimote/Android-Proximity-SDK#38]
Hi, I'm getting an error onResume of the App.

`
```
@Override
    public void onCreate() {

        super.onCreate();
        Log.d(TAG, "Created Proximity Service");
  


        proximityLiveData = new MutableLiveData<>();
        proximityMap = new HashMap<>();


        //Establish Cloud Credentials
        EstimoteCloudCredentials cloudCredentials = new EstimoteCloudCredentials(appId, appToken);
        proximityObserver = new ProximityObserverBuilder(this,cloudCredentials)
                .withOnErrorAction(new Function1<Throwable, Unit>() {
                    @Override
                    public Unit invoke(Throwable throwable) {
                        throwable.printStackTrace();
                        return null;
                    }
                })
                .withBalancedPowerMode()
                .build();


                //Build the location
                proximityZone = proximityObserver.zoneBuilder()
                        .forAttachmentKeyAndValue(location, locationName)//should be a variable
                        .inCustomRange(rangeInMeters)
                        .withOnEnterAction(new Function1<ProximityAttachment, Unit>() {
                            @Override
                            public Unit invoke(ProximityAttachment proximityAttachment) {

                                //Beacon onEnter of set Proximity
                                Log.d(TAG, "Found beacon! " + proximityAttachment.getDeviceId() + proximityAttachment.getPayload());
                                return null;
                            }
                        })
                        .withOnExitAction(new Function1<ProximityAttachment, Unit>() {
                            @Override
                            public Unit invoke(ProximityAttachment proximityAttachment) {
                                Log.d(TAG, "Exiting. " + proximityAttachment.getDeviceId() + proximityAttachment.getPayload());
                                return null;
                            }
                        })
                        .create();
        proximityObserver.addProximityZone(proximityZone);

    }

    @Override
    public void onStart(Intent intent, int startId) {
        super.onStart(intent, startId);
       proximityObserver.start();
    }
`
```

Main Activity
 ```
@Override
    protected void onStart() {

        bindService(serviceIntent,serviceConnection, Context.BIND_AUTO_CREATE);
        boundService = true;
        startService(serviceIntent);

        Log.d(TAG,"Started Main Activity");
        super.onStart();
}

```
    

> `W/System.err: io.reactivex.exceptions.UndeliverableException: java.lang.Exception: Bluetooth Low Energy scan failed with error code: 2
> W/System.err:     at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
> W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onError(ObservableFlatMap.java:573)
> W/System.err:     at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
> W/System.err:     at io.reactivex.observers.SerializedObserver.onError(SerializedObserver.java:155)
> W/System.err:     at io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.onError(ObservableDebounceTimed.java:104)
> W/System.err:     at io.reactivex.internal.operators.observable.ObservableRefCount$ConnectionObserver.onError(ObservableRefCount.java:134)
> W/System.err:     at io.reactivex.internal.operators.observable.ObservablePublish$PublishObserver.onError(ObservablePublish.java:184)
> W/System.err:     at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
> W/System.err:     at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
> W/System.err:     at io.reactivex.internal.operators.observable.ObservableRefCount$ConnectionObserver.onError(ObservableRefCount.java:134)
> W/System.err:     at io.reactivex.internal.operators.observable.ObservablePublish$PublishObserver.onError(ObservablePublish.java:184)
> W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.checkTerminate(ObservableFlatMap.java:495)
> W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:331)
> W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
> W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onError(ObservableFlatMap.java:571)
> W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:85)
> W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
> W/System.err:     at com.estimote.proximity_sdk.monitoring.estimote_monitoring.secure.SecureEstimoteMonitor$mergeWithEstimoteLocationScan$1$2.invoke(SecureEstimoteMonitor.kt:57)
> W/System.err:     at com.estimote.proximity_sdk.monitoring.estimote_monitoring.secure.SecureEstimoteMonitor$mergeWithEstimoteLocationScan$1$2.invoke(SecureEstimoteMonitor.kt:20)
> W/System.err:     at com.estimote.scanning_plugin.api.use_cases.ScanUseCase$notifyUserCallbacks$2.accept(ScanUseCase.kt:28)
> W/System.err:     at com.estimote.scanning_plugin.api.use_cases.ScanUseCase$notifyUserCallbacks$2.accept(ScanUseCase.kt:8)
> W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
> W/System.err:     at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
> I/chatty: uid=10317(liquid_studio.com.indoor_proximity) identical 2 lines
> W/System.err:     at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
> W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:85)
> W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
> W/System.err:     at com.estimote.scanning_plugin.packet_provider.scanner.PostLollipopEstimoteScanner$scan$1$callback$1.onScanFailed(PostLollipopEstimoteScanner.kt:30)
> W/System.err:     at android.bluetooth.le.BluetoothLeScanner$1.run(BluetoothLeScanner.java:547)
> W/System.err:     at android.os.Handler.handleCallback(Handler.java:790)
> W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
> W/System.err:     at android.os.Looper.loop(Looper.java:164)
> W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
> W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
> W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by pawelDylag** [comment]
Hey @JaoBiceps  - you should have filled all the necessary fields in the issue template. We need those information to proceed further (like phone type, sdk version, etc. ) Please fill the issue template correctly. 

As for your problem, you might try disabling additional features, like secure scanning, telemetry reporting, and analytics. You can do it bu building your `ProximityObserver` with the lines below:

``` Java
proximityObserver = new ProximityObserverBuilder(this,cloudCredentials)
                .withTelemetryReportingDisabled()
                .withAnalyticsReportingDisabled()
                .withEstimoteSecureMonitoringDisabled()
                .withOnErrorAction(new Function1<Throwable, Unit>() {
                    @Override
                    public Unit invoke(Throwable throwable) {
                        throwable.printStackTrace();
                        return null;
                    }
                })
                .withBalancedPowerMode()
                .build();
```

Please create a new issue and fill in all the necessary data from a template.
