### ISSUE TITLE
Scan while app in background

### ISSUE THREAD

**Issue by alaa7731** [Estimote/Android-Proximity-SDK#41]
## Prerequisites

* [X] done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** `1.4.0`

**Android devices affected:** 
1- Pixle 2 XL
2- Galaxy S6

**Android OS version affected:**
1- Oreo 8.1.0
2- Nougat 7.0

**Beacon hardware version:** G1.12 

## Description

I used Estimote SDK & Procimity SDK for searching for the beacons, and all is working well.

I was wondering if there's a way to keep the monitoring live even if the app is killed (without using foreground notification) as I need to trigger API call once I found the Beacon

**Comment by pawelDylag** [comment]
Hello @alaa7731 

Google is very much restricting background operations on recent Android versions. This is why scanning in the background without the foreground service is almost impossible starting from Android 7.0, so I'd better stop relying on this solution. 

You can use our `ProximityTrigger` that let's you achieve needed behaviour - [here is how to do it](https://github.com/Estimote/Android-Proximity-SDK#background-scanning-using-proximity-trigger-android-80). But be warned - it works on Android 8.0+ for now. 

Regards, 
Paweł

**Comment by alaa7731** [comment]
Hello @pawelDylag 

thanks for getting back to me this soon, yes I know, and am dividing my code if the version code is greater than 7.0 or not, before that is easy, I can use services and it's working.

my problem is above 7.0, and yea, about the `ProximityTrigger `, I read the topic, it works kind of what I need, but in my case I can't show notification, I need to call some API call when it's trigger for our backend

**Comment by pawelDylag** [comment]
Just an idea -> you can use `ProximityTrigger` method ` .triggerPendingIntentWhenInProximity()` and pass your own `PendingIntent` that can start foreground service with `ProximityObserver` to scan for your beacons. Then you can call your API in the defined `onEnterAction` :)

**Comment by alaa7731** [comment]
hmmmmmm, nice Idea.

will test it and get back to you with the results soon!
