### ISSUE TITLE
Beacon scan doesn't work with withBalancedPowerMode on Android 5.0 Api 21 Samsung Note 3

### ISSUE THREAD

**Issue by francisco-rg** [Estimote/Android-Proximity-SDK#44]
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have Bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** 0.4.1 and mustard:0.2.1

**Android devices affected:** Samsung Note 3 (so far)

**Android OS version affected:** Android Lollipop 5.0 (so far)

**Beacon hardware version:** F3.3 / Estimote OS 4.13.2 

## Description

When beacon scan start, never detect beacons, but it doesn't show error or start the scanning as per logs check.

We test our app, and also Estimote Proximity App on Git, but when you use 

        proximityObserver = ProximityObserverBuilder(applicationContext, cloudCredentials)
                .withScannerInForegroundService(notification)
                .withBalancedPowerMode()
                .build()

It doesn't work on our Samsung Note 3, Android 5.0.0 Api 21, there might be others. But it works only with:

        proximityObserver = ProximityObserverBuilder(applicationContext, cloudCredentials)
                .withScannerInForegroundService(notification)
                .withLowLatencyPowerMode()
                .build()

**(Optional) Steps to reproduce:**

1. Wait for first scan
2. check app logs and no error, or Bluetooth scanning message, and no event are fired (onEnter, onChange, onExit)

**Expected behavior:** Scan for beacons, zone event should be fired upon a beacon detection

**Actual behavior:** No zone event's are fired, or error show

**Comment by pawelDylag** [comment]
Hey @francisco-rg 

Thanks for reporting this. Samsung phones are super tricky to adjust to, because some of them work totally different than Android API documentation says so. We'll be adding more specific implementations soon, especially for those you mentioned. 

For now, you can help me by pasting this code into your activity's `onCreate` on your Samsung device and sending me the log result:

``` Kotlin
val btAdapter = (this.getSystemService(Context.BLUETOOTH_SERVICE) as BluetoothManager).adapter
Log.d("Offloaded filtering = ${btAdapter?.isOffloadedFilteringSupported}, Batch scanning: ${btAdapter?.isOffloadedScanBatchingSupported}")
```
I need to know if this model supports some handy features we use for scanning.  
Oh, and by the way, Android 5.0 had still pretty messy BLE stack, so possibly an update should help a little :)

Regards, 
Paweł

**Comment by francisco-rg** [comment]
MainActivity: [onCreate] Offloaded filtering = true, Batch scanning: false

**Comment by francisco-rg** [comment]
By the way, your test to find the problem, actually seems to be the mistake, after I place that, the scanner no longer works, after I comment the code it work again, that might be the clue to the real issue.

        BluetoothManager btManager = (BluetoothManager) this.getSystemService(Context.BLUETOOTH_SERVICE);
        BluetoothAdapter btAdapter = btManager != null ? btManager.getAdapter() : null;
        if ((logLevel <= Log.VERBOSE)) Log.v(TAG, "[onCreate] Offloaded filtering = " + (btManager != null ? btAdapter.isOffloadedFilteringSupported() : "") + ", Batch scanning: " + (btAdapter != null ? btAdapter.isOffloadedScanBatchingSupported() : ""));

Java of course hehehe

**Comment by pawelDylag** [comment]
Hey @francisco-rg 

Great, now I probably know what the problem is. My guess is that neither LOW_POWER and BALANCED power mode are working. Only LOW_LATENCY is scanning - am I right?

Our SDK doesn't have support for phones not supporting batch scanning - yet. I will add this to our backlog and will let you know when it is live :)

Regards, 
Paweł

**Comment by francisco-rg** [comment]
Hi @pawelDylag 

Good to hear that you had the idea of the problem, and yes you are right so far only works with LOW_LATENCY

Regards,
Francisco

**Comment by pawelDylag** [comment]
Hey @francisco-rg 

Check the version `0.4.4` - your phone should be working OK now. Let me know if everything is fine :)

Regards, 
Paweł

**Comment by francisco-rg** [comment]
Hey @pawelDylag , thanks again, testing, so far so good

**Comment by AjayDamco** [comment]
Hi @pawelDylag ,

I have the same problem with xamarin Estimote android sdk-0.11.0.(in visual studio -2017)
Beacon scanning is working and detecting beacons in Adnroid version below- 6, but in android version 7.0 or above OnBeaconsDiscovered() and StartRangingBeacons() both are scanning or running/executing but unable-to find any beacons even I am near to beacon? Please assist thanks in advance.

Regards,
Ajay

**Comment by pawelDylag** [comment]
Hey @AjayDamco. You are using our [old deprecated SDK](https://github.com/Estimote/Android-SDK). If you want to report an issue, you can post it there. Here we answer only questions about `ProximitySDK`.

Cheers!

**Comment by AjayDamco** [comment]
Hi @pawelDylag ,

Thanks for your reply, and sorry for posting here , as I mention that I am using **Xamarin Estimote SDK**
for C# development and downloaded from Nuget Package provided by Microsoft. and I don't think this is old for Xamarin as only 2 new version are available after this i.e : 0.11.0.1 and 1.0.3.

Thanks,
Ajay kumar
