### ISSUE TITLE
Crash when staring and connecting to Estimote Cloud, No beacons near by

### ISSUE THREAD

**Issue by francisco-rg** [Estimote/Android-Proximity-SDK#45]
## Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** Android-Proximity-SDK 0.4.3

**Android devices affected:** Galaxy A3

**Android OS version affected:** 5.0.2

**Beacon hardware version:** No beacons near by

## Description

Customer start app, when connecting to estimote cloud it crash, according to Crashlytics it was a timeout

The customer didn't had a near by beacon, but since it was on another country we can test with the same version with a beacon, the fact that one beacon wasn't near surely it's irrelevant.

**(Optional) Steps to reproduce:**

1. Start the app
2. Wait for the crash

**Expected behavior:** Not to crash

**Actual behavior:** Crash

## Additional information

If need we can provided access to crashlytics

Fatal Exception: io.b.c.d
timeout
io.reactivex.internal.observers.CallbackCompletableObserver.accept
Caused by java.net.SocketTimeoutException
timeout
arrow_right
okio.Okio$4.newTimeoutException (Okio.java:232)
okio.AsyncTimeout.exit (AsyncTimeout.java:275)
okio.AsyncTimeout$2.read (AsyncTimeout.java:243)
okio.RealBufferedSource.indexOf (RealBufferedSource.java:355)
okio.RealBufferedSource.readUtf8LineStrict (RealBufferedSource.java:227)
okhttp3.internal.http1.Http1Codec.readHeaderLine (Http1Codec.java:215)
okhttp3.internal.http1.Http1Codec.readResponseHeaders (Http1Codec.java:189)
okhttp3.internal.http.CallServerInterceptor.intercept (CallServerInterceptor.java:88)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.java:45)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:126)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
com.estimote.cloud_plugin.common.AuthorizationHeaderInterceptor.intercept (HttpInterceptors.kt:26)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
com.estimote.cloud_plugin.common.UserAgentHeaderInterceptor.intercept (HttpInterceptors.kt:16)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
com.estimote.cloud_plugin.common.ContentTypeHeaderInterceptor.intercept (HttpInterceptors.kt:9)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:200)
okhttp3.RealCall.execute (RealCall.java:77)

**Comment by pawelDylag** [comment]
Hey @francisco-rg 

This is a known issue, will be fixed in the upcoming releases. Thanks for reporting this :)

Regards, 
Paweł

**Comment by pawelDylag** [comment]
Hey @francisco-rg 

Short update - there is a bug in our internal Analytics module, that is causing this error. Fix will be ready next week - until that time you can use `.withAnalyticsReportingDisabled()` on your `ProximityObserverBuilder` to avoid having this crash :) 

Cheers, 
Paweł

**Comment by pawelDylag** [comment]
Hello!

Version `0.5.0` is now live with this issue fixed 🚀 
More info in our [CHANGELOG](https://github.com/Estimote/Android-Proximity-SDK/blob/master/CHANGELOG.md).  
Let me know about any other problems :)

Cheers, 
Paweł
