### ISSUE TITLE
onChangeAction won't get call on change of nearby attachment

### ISSUE THREAD

**Issue by cassiogec** [Estimote/Android-Proximity-SDK#46]
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** Android-Proximity-SDK 0.4.4

**Android devices affected:** Xiaomi Mi 5s

**Android OS version affected:** Android 7.0

**Beacon hardware version:** G1.8

## Description
I am having some problems with the onChangeAction, i have done the exact same thing as the example on README.md. I have a main region for enter and exit actions(it's working perfectly), and one zone to control which beacon is nearby. But i don't get the onChangeAction for change of nearby attachments, i only receive the ones with after exit and enter. I had already tried changing the custom range, and the power modes.
PS: I am leaving the beacons far from each other, and to try i went as close as possible to the beacon.
PS 2: English is not my main language, please excuse any errors on my part.

**Expected behavior:** Receive a onChangeAction when i am closer to a beacon than the other.

**Actual behavior:** Not receiving the onChangeAction

## Additional information
**My Code**:
`
        mProximityObserver = new ProximityObserverBuilder(mContext, cloudCredentials)
                .withLowLatencyPowerMode()
                .withEstimoteSecureMonitoringDisabled()
                .withTelemetryReportingDisabled()
                .withAnalyticsReportingDisabled()
                .withOnErrorAction(new Function1<Throwable, Unit>() {
                    @Override
                    public Unit invoke(Throwable throwable) {
                        mBeaconObserver.onError(throwable);
                        return null;
                    }
                })
                .build();

        mProximityZones = new ArrayList<>();
      
     for (Map<String, Object> map : listBeacons) {
            mProximityZones.add(mProximityObserver.zoneBuilder()
                    .forAttachmentKeyAndValue("beaconRegion", map.get("identifier").toString())
                    .inCustomRange(5)
                    .withOnEnterAction(new Function1<ProximityAttachment, Unit>() {
                        @Override
                        public Unit invoke(ProximityAttachment proximityAttachment) {
                            mBeaconObserver.onBeaconEnter(proximityAttachment);

                            return null;
                        }
                    })
                    .withOnExitAction(new Function1<ProximityAttachment, Unit>() {
                        @Override
                        public Unit invoke(ProximityAttachment proximityAttachment) {
                            mBeaconObserver.onBeaconExit(proximityAttachment);
                            return null;
                        }
                    })
                    .create());
        }

        mProximityZones.add(mProximityObserver.zoneBuilder()
            .forAttachmentKeyAndValue("region", "main")
            .inCustomRange(5)
            .withOnChangeAction(new Function1<List<? extends ProximityAttachment>, Unit>() {
                @Override
                public Unit invoke(List<? extends ProximityAttachment> proximityAttachments) {
                    

                    List<ProximityAttachment> list = new ArrayList<>(proximityAttachments);
                    mBeaconObserver.onBeaconChangeStatus(list);

                    return null;
                }
            })
            .create());

        mProximityObserver.addProximityZones(mProximityZones);`

PS 3: I had to use the .ithEstimoteSecureMonitoringDisabled(), withTelemetryReportingDisabled() and withAnalyticsReportingDisabled(), because i was getting  the "Bluetooth Low Energy scan failed with error code: 2", but the onChangeAction was not working even before.

**Comment by pawelDylag** [comment]
Hey @cassiogec 

Does all your beacons have attachment `region:main` associated in the Estimote Cloud? 
Every beacon should have two attachments added: `beaconRegion:XXX` and `region:main` for your use case to work :) 

Let me know about this, and we will proceed further :)

**Comment by cassiogec** [comment]
Yes, they have.
I actually receive some onChangeAction, but not the ones of change of distance. I receive the ones after the enter and exit actions. For example, when a beacon enter the zone, i receive the onEnterAction and the onChangeAction. But when i get closer to this beacon, i don't receive another for change of nearby attachment.
I was thinking that maybe i have to do some different configuration on my beacons.

**Comment by cassiogec** [comment]
I am sorry if i am not making myself clear, But for example, when we have the AB attachments, and i get closer to B but still detects A, i wont get a onChange to BA attachments?

Because this is written on the annotation and its not happening to me.

*This action will be called whenever a change occurs inside a zone.
Let's say we have two beacons - A and B, both having the same zone defined by key/value
 pair "venue":"office".
If somebody enters the proximity of beacon A, the `onEnterAction` is called for the whole zone.
If that person walks away from beacon A and goes to beacon B, the zone is still maintained,
so no `onExitAction` will be called yet. However, there was a change inside the zone,
so the current nearby attachments have changed (from beacon A to B). This is where
`onChangeAction` gets called. It helps you to track the current nearby attachments
 inside a zone.*

**Comment by cassiogec** [comment]
OK, i understand you, i got confused on the translation :smile:  , because on the README it says that it **helps to track the ones that are nearby inside the zone** so i thought that maybe it would track the distance as well.

There is a way that i could track the distance? Because the old API that will be deprecated, i could get an approximate distance.

**Comment by pawelDylag** [comment]
Well, we have intentionally removed explicit distances from our new API. The fact is, that you may never precisely deliver exact distances on top of BLE due to the radio waves nature. This is why we are trying to change our developers mindset to think much more about "zones" and not "distances".  This is also why I encourage people to use our predefined `inFarRange()` or `inNearRange`. The fact is, that the calculated distance will always be an `estimation` that will always have an error margin - and we don't want to promise something we know won't be true :)

Thanks for the feedback about the documentation in our example - I will think how to improve it not to confuse anyone anymore :)

**Comment by cassiogec** [comment]
I agree, but the estimation or the nearby track in my case would work just fine.

Thank you for the help and the quick replay.
