### ISSUE TITLE
proximity observer error

### ISSUE THREAD

**Issue by rasool182716** [Estimote/Android-Proximity-SDK#49]
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** 0.5.0

**Android devices affected:** Samsung Galaxy A3 - 7.0 and HTC 6.0

**Android OS version affected:** 7.0, 6.0 and 5.1

**Beacon hardware version:** F3.3

## Description

App always crashing in withOnErrorAction method. It says below error.

proximity observer error: com.estimote.proximity_sdk.exception.NoBeaconsForGivenZonesException: No beacons for given attachment/tag values. Make sure you've entered attachment/tag names correctly, your app has network connection available (at least once), and attachments/tags are correctly assigned to your beacons in the Estimote Cloud.

**Expected behavior:** It should not crash even if its not connected. Also need to know why its not connected with beacons when iOS app is connected with it and working fine on Enter and Exit.

**Actual behavior:** Not connecting with beacons and app gets crashed.

## Additional information
**Using JAVA with Android Project not Kotlin**

![image](https://user-images.githubusercontent.com/29065598/39702390-48ba88de-5222-11e8-90ff-89bbb1c87f29.png)

**Comment by Raj1015120** [comment]
Can you please tell me how you have resolved this issue ? Piece of code will help me. 

Thanks in advance.

**Comment by rasool182716** [comment]
Please initialise your beacons monitoring code in following method "**new Function0<Unit>() {**" at 
**RequirementsWizardFactory**

For more details please follow default template coding from your dashboard  -  Apps -> Add New App -> Choose the kind of app you want to add -> Use This Template -> Choose your platform -> Continue -> Download Template
