### ISSUE TITLE
Telemetry data not being sent

### ISSUE THREAD

**Issue by Goncalo-Almeida** [Estimote/Android-Proximity-SDK#52]
## Prerequisites

* [X] My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
* [X] My Android device/devices supports BLE and has Android OS version >= 5.0.0 
* [X] My Android device/devices have bluetooth enabled
* [X] My app has Location Permissions granted
    
## Basic information

**Proximity SDK version:** `0.5.1`

**Android devices affected:** `Blackview BV600`

**Android OS version affected:** `Nougat 7.0`

**Beacon hardware version:** `F3.3`

**Beacon firmware version:** `4.14.1`

## Description

I'm not seeing any updates on Telemetry data in the Estimote Cloud platform. I'm **not** using `withTelemetryReportingDisabled`.

**Steps to reproduce:**

1. Create a `ProximityObserver`
My code:
```
private val cloudCredentials = EstimoteCloudCredentials(ESTIMOTE_APP_ID, ESTIMOTE_APP_TOKEN)
private val proximityObserver = ProximityObserverBuilder(mActivity, cloudCredentials)
            .withBalancedPowerMode()
            .withOnErrorAction { System.err.println("opps! erro!") }
            .build()

private val venueZone = proximityObserver.zoneBuilder()
            .forAttachmentKeyAndValue("company", "vasp")
            .inFarRange()
            .withOnEnterAction { println("Entered: " + it.getPayload()["local"]) }
            .withOnExitAction { println("Exited: " + it.getPayload()["local"]) }
            .withOnChangeAction { it.forEach { println("Changed: ${it.getPayload()["local"]}") } }
            .create()

private var observationHandler: Handler? = null

RequirementsWizardFactory.createEstimoteRequirementsWizard().fulfillRequirements(
                mActivity,
                onRequirementsFulfilled = {
                    observationHandler = proximityObserver.addProximityZone(venueZone).start()
                },
                onRequirementsMissing = { println("onRequirementsMissing") },
                onError = { println("onError") })
```
2. Wait to see which beacon got detected
3. Check beacon on the Estimote Cloud platform and notice there isn't new telemetry data

**Expected behavior:** Telemetry is sent to Estimote Cloud

**Actual behavior:** Telemetry is not sent to Estimote Cloud

## Additional information
Telemetry data seems to be either sent or aggregated hourly, I took that into account and tested in different hours throughout the day.
I used the iOS Estimote App and the telemetry data is only sent if I select the beacon from the list and connect to it.
Should I be doing anything else?

Off-topic:
Also, where do I submit Issues with the mobile apps and the Estimote Cloud platform?

**Comment by jan-osch** [comment]
> Actual behavior: Telemetry is not sent to Estimote Cloud
How do you know that data is not sent to Estimote Cloud? Do you use some kind of debug proxy?

**Comment by pawelDylag** [comment]
Hey @Goncalo-Almeida 

Thanks for the report. I will discuss this with our cloud magicians, and will try to double-check it in our SDK. To make sure that the data is being sent, you can temporary enable debug logs from our telemetry reporter. Our SDK uses an external logging tool called `Skald`. Just add this lines to your application class:

```Kotlin
class YourAppExtendingClass : Application() {

    override fun onCreate() {
        super.onCreate()
        skald {
            writeSaga {
                toLogcat { withTag { "TelemetryCheck" } }
                withPath { "com.estimote.proximity_sdk.telemetry_reporter" }
                withLevel { LogLevel.DEBUG }
                withPattern { "${it.simplePath} -> ${it.message}" }
            }
        }
    }
}
```
Then you should see some Logcat logs about telemetry data being reported. We need to make sure, that there are logs there about success :)

Kind regards, 
Paweł

**Comment by Goncalo-Almeida** [comment]
Thank you both for the quick response.

@jan-osch: Sorry for the inaccurate statement. I meant that I can't see new telemetry data in the Estimote Cloud  platform. 

Hi @pawelDylag,
I'm not seeing any entries about telemetry data being reported.

I'm using Android Studio 3.1.2 and I simply searched for TelemetryCheck (the tag). I'm filtering messages for the app being debug only, and the log level is set to Debug.

I didn't have an Application class, so I created one and added it to the Manifest.
The debugger does stop at the breakpoint I put in the second line of the onCreate function.

Am I forgetting anything?

**Comment by pawelDylag** [comment]
I've double checked - the snippet above is correct and it should display logs. 
1. A super basic question - does your beacon have Estimote Telemetry packet advertising enabled in our Cloud?
2. Could you share with me your email on which your beacons are registered? (You can PM it to me). We'll check if data from your beacons is being reported.

Cheers!

**Comment by Goncalo-Almeida** [comment]
Hey!

1. The Estimote Telemetry was enabled but I disabled it and then re-enabled for one of the beacons. I have no idea why, but then it worked for all beacons except one.

2. I'll PM you de e-mail right now.

The telemetry information was still not showing on Estimote Cloud for one of the beacons. After I connected to the beacon using the iOS Estimote app, and disabled and re-enabled the Telemetry packet, it updated the Telemetry packet on Estimote Cloud.

It seems like there is no issue here, but I don't know what went wrong the first time.
So I guess you can close this and I'll report back here if I find myself in trouble again :)

Cheers 👍
