### ISSUE TITLE
SDK Version 0.6.0 Example App Crashing

### ISSUE THREAD

**Issue by zack-hable** [Estimote/Android-Proximity-SDK#59]
## Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** 0.6.0

**Android devices affected:** Samsung Galaxy S8

**Android OS version affected:** Oreo 8.0.0

**Beacon hardware version:** G1.12

## Description

After launching the example app and the scanner notification pops up the app crashes.

**Expected behavior:** Example app normal functionality (areas being shaded depending on if the phone is within the beacon)

**Actual behavior:** app crashes

## Additional information
The app works fine/as expected on SDK version 0.5.0
[log.txt](https://github.com/Estimote/Android-Proximity-SDK/files/2112966/log.txt)

**Comment by pawelDylag** [comment]
Hey @zack-hable 

Stupid mistake, gonna be fixed soon :) 
It only happens when you don't have proper tags associated to you beacons in Estimote Cloud. 

Thanks for reporting this!
Regards, 
Paweł

**Comment by zack-hable** [comment]
It seems to work as expected when all of the zones are setup correctly.  Any ideas on #60 ?

**Comment by tzuviatwork** [comment]
We managed to workaround this problem.
Edit beacon settings through estimote cloud, so that the beacon has at least one attachment with value equal to tag. 
If your code uses  .forTag("tag") it works. 
Indeed the error reporting callback needs not to trigger UI action. we changed it to just log.

**Comment by pawelDylag** [comment]
Fixed in `0.6.1` :)
