### ISSUE TITLE
Xamarin Estimote SDK -0.11.0 for Android version -7 is not scanning beacons (in Visual Studio -2017) 

### ISSUE THREAD

**Issue by AjayDamco** [Estimote/Android-Proximity-SDK#63]
## Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version = 7.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** Xamarin Estimote Android- 0.11.0

**Android devices affected:** Moto C Pluse, 

**Android OS version affected:** 7

**Beacon hardware version:** [Paste here your beacons hardware version (you can check that in Estimote Cloud).] 

## Description

I have the same problem with Xamarin Estimote android sdk-0.11.0.(in visual studio -2017)
Beacon scanning is working and detecting beacons in Android version below- 6, but in android version 7.0 or above OnBeaconsDiscovered() and StartRangingBeacons() both are scanning or running/executing but unable-to find any beacons even I am near to beacon I always have beacon count 0.

(It is working for other version of Android).

![xamarin extimote sdk](https://user-images.githubusercontent.com/13217744/42437030-6a4eb488-8379-11e8-9b00-d4810bc7c523.png)
## Additional information
```
I am using Xamarin Estimote SDK for development in C# not for Java and there is only few version of SDK available for Xamarin.


Thanks,
Ajay kumar
```

**Comment by pawelDylag** [comment]
It's not a problem with Proximity SDK. You are using our old deprecated SDK. Please consider posting an issue there -> https://github.com/Estimote/Android-SDK
Closing.
