### ISSUE TITLE
Recommended way to do secure iBeacon ranging?

### ISSUE THREAD

**Issue by 1b0t** [Estimote/Android-Proximity-SDK#64]
Hi There,

since the `Estimote-SDK` is deprecated I was wondering what the recommended way is to do *ranging of secureUUID Beacons* with this SDK?

Basically, all I want to do is range for a set of beacons with the same (secured) UUID and wildcard major and minor values (`null`).

After reading through the documentation I can't figure out how to do this efficiently (apart from scanning for all telemetry packets and resolving beacons manually).

Can somebody help figure this out? Maybe I'm just missing something.

**Comment by pawelDylag** [comment]
Hey @1b0t 

`ProximitySDK` allows you to use `Secure Estimote Monitoring`.
You can read more [here](https://blog.estimote.com/post/172115262320/presence-verification-and-security-is-more-refined), and [here](https://community.estimote.com/hc/en-us/articles/360002194771-How-to-enable-Estimote-Secure-Monitoring) :)

Cheers!

**Comment by 1b0t** [comment]
I've already setup the secureUUIDs and it's working flawlessly on iOS.

The question is how do I build a proximity zone based on the UUID and start ranging for those beacons?

What would be the equivalent of:


        beaconManager = new BeaconManager(MainApplication.instance.getApplicationContext());

        beaconManager.setRangingListener(new BeaconManager.BeaconRangingListener() {
            public void onBeaconsDiscovered(BeaconRegion region, final List<Beacon> beacons) {
                Log.d( "BEACON", "Ranged beacons ("+ beacons.size() + "): " + beacons);
            }
        });

        beaconManager.connect(new BeaconManager.ServiceReadyCallback() {
            @Override public void onServiceReady() {
                beaconManager.startRanging(new SecureBeaconRegion("regionId", UUID.fromString("EEEEEEEE-DDDD-AAAA-0000-CCCCEEEEBBBB"), null, null));
            }
        });

**Comment by pawelDylag** [comment]
You can add attachments to your beacons to mirror the UUID data. For example, each beacon can have an attachment set:

`UUID`:`EEEEEEEE-DDDD-AAAA-0000-CCCCEEEEBBBB`
`MAJOR`:`111`
`MINOR`:`1`

with major and minor data varying regarding the individual beacons.  You can access this data through `onChangeAction` which reports the list of `ProximityContext` around you. Each `ProximityContext` object contains data for one individual beacon, like attachments, tags, or device identifier.
In this way you can create the similar experience without breaking your existing SecureUUID iBeacon infrastructure.

**Comment by 1b0t** [comment]
I see. If I'm not mistaking those tags are only available online (through Estimote Cloud) and not broadcast by the beacons directly, correct? (This would not require an update to the (physical) beacons through the deployment app?)

**Comment by pawelDylag** [comment]
@1b0t  yes, tags are only available online. No update for your beacons needed. Although remember, that `Estimote Secure Monitoring` is supported by hardware versions:  F3.3, G1.12, I1.2, J1.6 and newer.

**Comment by 1b0t** [comment]
@pawelDylag ok, I'll try to implement it that way.

Thanks for your support!

**Comment by pawelDylag** [comment]
For the sake of clarity, I'm closing this issue. If any other questions would emerge, please don't hesitate to reopen this/post new issue. 

Cheers, 
Paweł
