### ISSUE TITLE
Background scanning using Proximity Trigger (Android 8.0+) is not working

### ISSUE THREAD

**Issue by rasool182716** [Estimote/Android-Proximity-SDK#65]
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** 0.6.2

**Android devices affected:** Nokia TA-1043 

**Android OS version affected:** 8.1.0

**Beacon hardware version:** F3.3

## Description

Background scanning using Proximity Trigger (Android 8.0+) is not working. Please find my below code.

mNotif = new NotificationCompat.Builder(this, "content_channel")
                .setSmallIcon(android.R.drawable.ic_dialog_info)
                .setContentTitle("Beacon scan")
                .setContentText("Scan is running...")
                .setContentIntent(PendingIntent.getActivity(this, 0,
                        new Intent(this, MainActivity.class), PendingIntent.FLAG_UPDATE_CURRENT))
                .setPriority(NotificationCompat.PRIORITY_HIGH)
                .build();

        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
            new ProximityTriggerBuilder(this)
                    .displayNotificationWhenInProximity(mNotif)
                    .withNotificationId(111)
                    .build()
                    .start();
        }

**(Optional) Steps to reproduce:**

1. Enable Bluetooth and Location
2. Open the app and then force close it
3. Move close to the beacons

**Expected behavior:** Notification should be shown

**Actual behavior:** No Notification shown

**Comment by zack-hable** [comment]
I've already reported this issue here: #60

**Comment by pawelDylag** [comment]
Hey guys - we're not working on ProximityTrigger for now - got lots of other priority stuff to do. I'll add this to my backlog, and will take a look at this for sure! 

My guess is that there was any additional restriction put on the background functionalities in Android `8.1.0` . `ProximityTrigger` was tested on `8.0.0`, and we need to re test it on `8.1.0`. Will definitely let you know about the progress when I hit this task :)

Cheers, 
Paweł

**Comment by rasoolmohamed** [comment]
Hi pawelDylag,
  Please provide update on above issue.

**Comment by AndroidDeveloperMCT** [comment]
Any update on this issue ?
