### ISSUE TITLE
Incompatible Skald version with IndoorSDK

### ISSUE THREAD

**Issue by Amanr790** [Estimote/Android-Proximity-SDK#69]
## Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** 0.6.2

**Android devices affected:** Moto Devices

**Android OS version affected:** Above 5.0

**Beacon hardware version:** F3.3
## Description

App Crashes while monitoring for multiple beacons having same tags

proximityObserver =
                    new ProximityObserverBuilder(context, ((ACVipsApplication) context.getApplicationContext()).getEstimoteCloudCredentials())
                            .withOnErrorAction(new Function1<Throwable, Unit>() {
                                @Override
                                public Unit invoke(Throwable throwable) {
                                    Log.e("app", "proximity observer error: " + throwable);
                                    return null;
                                }
                            })
                            .withScannerInForegroundService(goodbyeNotification)
           
                            .withBalancedPowerMode()
                            .build();

            ProximityZone zone = proximityObserver.zoneBuilder()
                    .forTag("candy_1")
                    .inNearRange()
                    .withOnChangeAction(new Function1<List<? extends ProximityContext>, Unit>() {
                        @Override
                        public Unit invoke(List<? extends ProximityContext> proximityContexts) {
                            notificationManager.notify(notificationId, helloNotification);
                            return null;
                        }
                    })
                    /* .withOnEnterAction(new Function1<ProximityContext, Unit>() {
                         @Override
                         public Unit invoke(ProximityContext proximityContext) {
                             notificationManager.notify(notificationId, helloNotification);
                             return null;
                         }
                     })
                     .withOnExitAction(new Function1<ProximityContext, Unit>() {
                         @Override
                         public Unit invoke(ProximityContext proximityContext) {
                             notificationManager.notify(notificationId, goodbyeNotification);
                             return null;
                         }
                     })*/
                    .create();
            proximityObserver.addProximityZone(zone);   
            proximityObserver.start();

## Additional information
Crash Report: 
USER_COMMENT=null
ANDROID_VERSION=6.0
APP_VERSION_NAME=1.2
BRAND=motorola
PHONE_MODEL=XT1706
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
at android.os.Handler.handleCallback(Handler.java:822)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5769)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
Caused by: java.lang.NoSuchMethodError: No interface method debug(Ljava/lang/String;)V in class Lcom/wafel/skald/api/SkaldLogger; or its super classes (declaration of 'com.wafel.skald.api.SkaldLogger' appears in /data/app/com.pfes-2/base.apk:classes50.dex)
at com.estimote.proximity_sdk.telemetry_reporter.RxTelemetryReporter$postTelemetryDataToCloud$1$1.run(RxTelemetryReporter.kt:38)
at io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:54)
at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:90)
at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
... 7 more
java.lang.NoSuchMethodError: No interface method debug(Ljava/lang/String;)V in class Lcom/wafel/skald/api/SkaldLogger; or its super classes (declaration of 'com.wafel.skald.api.SkaldLogger' appears in /data/app/com.pfes-2/base.apk:classes50.dex)
at com.estimote.proximity_sdk.telemetry_reporter.RxTelemetryReporter$postTelemetryDataToCloud$1$1.run(RxTelemetryReporter.kt:38)
at io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:54)
at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:90)
at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
at android.os.Handler.handleCallback(Handler.java:822)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5769)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)

**Comment by pawelDylag** [comment]
It seems that you are using outdated [Skald](https://github.com/wafel82/Skald) library in your application. Either remove it, or update to the latest version and see if that helps. 

Cheers, 
Paweł

**Comment by Amanr790** [comment]
Hello pawel ,
I am not using any library related to SkaId in the Application .

my gradle dependencies are :
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile "com.android.support:design:${rootProject.ext.appcompat_support}"
    compile "com.android.support:appcompat-v7:${rootProject.ext.appcompat_support}"
    compile "com.android.support:recyclerview-v7:${rootProject.ext.appcompat_support}"
    compile 'de.hdodenhof:circleimageview:2.2.0'
    compile 'br.com.simplepass:loading-button-android:1.8.3'
    compile 'me.relex:circleindicator:1.2.2@aar'
    compile "ch.acra:acra:${rootProject.ext.acra}"
    compile "com.android.support:multidex:${rootProject.ext.multidex}"
    /*compile "com.google.android.gms:play-services:12.0.1"*/


    compile "com.github.bumptech.glide:glide:${rootProject.ext.glide}"

   //Firebase Messaging
    compile "com.google.firebase:firebase-core:${rootProject.ext.firebase_core}"
    compile "com.google.firebase:firebase-iid:${rootProject.ext.firebase_iid}"
    compile "com.google.firebase:firebase-messaging:${rootProject.ext.firebase_messaging}"
    /*compile "com.google.firebase:firebase-auth:17.1.0"*/
    compile project(path: ':fblibrary')
    compile project(path: ':shimmer')

    //Retrofit

    compile "com.squareup.retrofit2:retrofit:${rootProject.ext.retrofit}"
    compile 'com.squareup.retrofit2:converter-jackson:2.4.0'
    compile "com.fasterxml.jackson.core:jackson-databind:${rootProject.ext.retrofit_converter_jackson}"
    compile "com.fasterxml.jackson.core:jackson-core:${rootProject.ext.retrofit_converter_jackson}"
    compile "com.fasterxml.jackson.core:jackson-annotations:${rootProject.ext.retrofit_converter_jackson}"



  //  compile 'com.chauthai.swipereveallayout:swipe-reveal-layout:1.4.0'
/*
    compile 'com.google.code.gson:gson:2.6.1'
*/



   // compile 'jp.wasabeef:blurry:2.1.1'



    // PlayServices
    compile "com.google.maps.android:android-maps-utils:${rootProject.ext.utils}"
    compile "com.google.android.gms:play-services-maps:${rootProject.ext.play_services}"
    compile "com.google.android.gms:play-services-location:${rootProject.ext.play_services}"
    compile "com.google.android.gms:play-services-places:${rootProject.ext.play_services}"
  //  compile 'com.airbnb.android:airmapview:1.3.0'
  //  compile 'com.github.jd-alexander:library:1.1.0'
    compile "com.android.support.constraint:constraint-layout:${rootProject.ext.constraint_layout}"
    testCompile 'junit:junit:4.12'

    //ButterKnife
    compile "com.jakewharton:butterknife:${rootProject.ext.butterknife}"
    compile "com.jakewharton:butterknife:${rootProject.ext.retrofit_converter_jackson}"
    apt "com.jakewharton:butterknife-compiler:${rootProject.ext.butterknife}"

    //Estimote
   // compile 'com.estimote:sdk:1.4.1'
    compile 'com.estimote:proximity-sdk:0.6.2'
    compile 'com.estimote:indoorsdk:2.5.2'
    compile 'com.estimote:mustard:0.2.1'
}

**Comment by pawelDylag** [comment]
Ok, now I see - you are using `indoorsdk` which uses older version of Skald library than `ProximitySDK`. We will need to update Skald library in our `IndoorSDK` to match the latest version. If you are not using indoor sdk in your project, just simply remove it from your dependencies. Otherwise you have to wait for the new `IndoorSDK` version - I'll add this to our backlog. 

Cheers, 
Paweł

**Comment by Amanr790** [comment]
Can you please give an estimation on when will the new Indoor SDK version will be available?
Thanks and Regards,
 Aman

**Comment by Walt-H** [comment]
@pawelDylag What are the implications of this compatibility?

**Comment by pawelDylag** [comment]
@Walt-H  I don't understand what you mean by `implications`? The probably answer would be "The implication of this is that both SDK can work together without any errors".  So both SDK's can be compiled together without any problems. If you run into any issues in runtime, then please notify us about it :)
