### ISSUE TITLE
How to find nearest beacon

### ISSUE THREAD

**Issue by ldimitroff** [Estimote/Android-Proximity-SDK#76]
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * My beacons have Estimote Monitoring enabled (Check it in the Estimote Cloud, or via app)
    * My Android device/devices supports BLE and has Android OS version >= 5.0.0 
    * My Android device/devices have bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** [estimote:proximity-sdk:1.0.0]

**Android devices affected:** [Samsung]

**Android OS version affected:** [6.0.1, 7.0.0, 8.0]

**Beacon hardware version:** [F3.3] 

## Description

Re-Opening [Issue-73](https://github.com/Estimote/Android-Proximity-SDK/issues/73) Because there's no real anwser. 
My app shows content ordered by closest beacon firts, I need to have the knowledge at every time witch beacon is the closest in order to display information to the user. 

I am able to find all the beacons using Tag Name, But How to find nearest beacon among them ?

Thanks

**Comment by pawelDylag** [comment]
Hey @ldimitroff 

**Simple answer** - you can't. The `ProximityObserver` is by design not reporting ranges to beacons nearby. 

**Advanced answer** - you can write your custom logic on top of RSSI using our `BluetoothScanner`. Here's how you can get the updates of every `Estimote Monitoring` packet received with RSSI values already smoothed (it uses Estimote Location underneath, so this is why it's called like this):

``` Kotlin  
  val bluetoothScanner = EstimoteBluetoothScannerFactory(applicationContext)
                .getSimpleScanner()
  
  val scanHandle = bluetoothScanner
                .estimoteLocationScan()
                .withLowLatencyPowerMode()
                .withOnPacketFoundAction {
                  // HERE YOU ARE NOTIFIED ABOUT EVERY PACKET 
                  val rssi = it.rssi
                  val estimoteDeviceId  it.deviceId
                  // do something here...
                }
                .withOnScanErrorAction {
                    Log.e("LOC", "Scan failed: $it")
                }
                .start()

    ...
 
    // don't forget to stop the scanning!
    scanHandle.stop()

**Comment by Walt-H** [comment]
@ldimitroff I am working on a proximity app that needs to unambiguously know where the user is at in select areas. It's different than having the closest beacon, but maybe you can build off this idea.

I make **<= 0.5** meter zones, and if I still see more than one beacon in the same context, I "tune" the beacons, weakening the signal strength of the beacon under scrutiny.

**Comment by happyssm90** [comment]
@ldimitroff  Did you find any solution for finding nearest beacon using V1.0.0 SDK ?

**Comment by pawelDylag** [comment]
@happyssm90  I would start with this https://en.wikipedia.org/wiki/Trilateration  :)

**Comment by ldimitroff** [comment]
Wow, super helpful information. Seems that I need more help with this:
```scanHandler = bluetoothScanner
                    .estimoteLocationScan()
                    .withLowLatencyPowerMode()
                    .withOnPacketFoundAction(onPacketFoundAction)
                    .start();```

```
private Function1<? super EstimoteLocation, Unit> onPacketFoundAction = new Function1<EstimoteLocation, Unit>() {
        @Override
        public Unit invoke(EstimoteLocation estimoteLocation) {
            WbLogger.i(String.format("Estimote Location Found: Device ID %s, MeasuredPower %s", estimoteLocation.getDeviceId(), estimoteLocation.getMeasuredPower()));
            return null;
        }
    };
```
But in the console I always get: 
```08-14 11:49:34.526 : Estimote Location Found: Device ID FF844E3525A4013749CDE4D40631362B, MeasuredPower -62
08-14 11:49:35.559 :Estimote Location Found: Device ID FF844E3525A4013749CDE4D40631362B, MeasuredPower -62
.....
08-14 11:51:26.916 : Estimote Location Found: Device ID FF844E3525A4013749CDE4D40631362B, MeasuredPower -62
......
08-14 12:01:24.375: Estimote Location Found: Device ID FF844E3525A4013749CDE4D40631362B, MeasuredPower -62
```
While I'm moving around always getting the same MeasuredPower. What am I doing wrong?

**Comment by pawelDylag** [comment]
Hello @ldimitroff 

Measured power is a constant value for the given beacon. In simple words, it's your beacon's RSSI measured at the distance of 1 meter. It's a constant that you could use when estimating a distance to the beacon. Have in mind that it's a very rough approximation!

Cheers!
