### ISSUE TITLE
check if scanning is currently running / avoid double start

### ISSUE THREAD

**Issue by stephandue** [Estimote/Android-Proximity-SDK#8]
Is it possible to see if the ProximityObserver.Handler is already active? I had some scenarios where I obviously started it twice and therefor got enter / exit calls twice.

Many Thanks
Stephan

**Comment by pawelDylag** [comment]
`ProximityObserver.Handler` is intended to be state-less. So whenever you call `start()` on your `ProximityObserver`, it will start active scanning until you call `handler.stop()`.  This state-less architecture allows to avoid many state-related bugs/problems/issues. I suggest building your app logic to avoid starting more then one scan. If you have any use-case that is hard to tackle with such mechanism, please share it with me :)

Regards, 
Paweł
