### ISSUE TITLE
How to get Major and Minor Id of a Beacon from DevieId

### ISSUE THREAD

**Issue by Amanr790** [Estimote/Android-Proximity-SDK#82]
## Description
I want to get major and minor Id from the mentioned ProximityContext Device Id . Can you please suggest how can i do that ? 
I am Using Proximity Sdk 

ProximityZone zone = proximityObserver.zoneBuilder()
                .forTag("candy_1")
                .inCustomRange(3.0)
                .withOnChangeAction(new Function1<List<? extends ProximityContext>, Unit>() {
                    @Override
                    public Unit invoke(List<? extends ProximityContext> contexts) {
// Device Id                       
 contexts.get(0).getInfo().getDeviceId()
// get Major and Minor Id
                        return null;
                    }
                })
                .create();

I solutions i found have been deprecated .

**Comment by pawelDylag** [comment]
Hey!

`Major` and `Minor` are concepts used in `iBeacon` protocol. Our ProximitySDK doesn't use `iBeacon`, but our own custom packet called `Estimote Monitoring`. There is no such thing as `minor/major` there. 

You can use `attachments` to add additional information to your zones. Read more about it here -> https://github.com/Estimote/Android-Proximity-SDK#optional-adding-attachments-to-your-beacons

Cheers!
Paweł
