### ISSUE TITLE
Exit beacon when app in background

### ISSUE THREAD

**Issue by hardikpatel0884** [Estimote/Android-Proximity-SDK#85]
hello here i am using 'com.estimote:proximity-sdk:1.0.3'
my app working fine in foreground when when i put my app in background it autometically exit from beacon after 2-3 min even when beacon is near to device and when unlock/wake device it started with Enter it self 
i have used foreground service to run my logic

**Comment by pawelDylag** [comment]
Please provide us with all the necessary information included in an Issue template. This allows us to save a lot of time on asking additional questions. 

Paweł
