### ISSUE TITLE
Huawei p10 lite sometimes only triggers enter or exit when screen is on

### ISSUE THREAD

**Issue by stephandue** [Estimote/Android-Proximity-SDK#9]
With the old SDK´s i always had the problem that most Huawei Phones don´t trigger enter or exit events when the screen is off.
With this new Proximity SDK for the first time events are triggered even when the screen is off. However not always. It feels like there´s a maximum scanning time and it get´s stopped automatically after a period. But I can´t really find a pattern.
Is there any knowledge about this?

Thanks!
Stephan

**Comment by pawelDylag** [comment]
Hey @stephandue 

This is interesting. Have you tried building your `ProximityObserver` with option `.withScannerInForegroundService(notification)`? This should prevent the system from killing/stopping your scan. 

What is more, Android bluetooth implementation is automatically changing the scan parameters if the scan was started without hardware filters. This is peculiar, because some phones are not supporting offloaded filtering, and I'm curious what happens in that case - maybe your phone is affected. 
Could you please paste the code below to your activity? Then run it on your P10 lite and send me the result logs. 
```Kotlin
        val btManager = getSystemService(Context.BLUETOOTH_SERVICE) as BluetoothManager
        Log.d("BLUETOOTH CHECK", "Is offloaded filtering supported: ${btManager.adapter?.isOffloadedFilteringSupported}")
        Log.d("BLUETOOTH CHECK", "Is offloaded scan batching supported: ${btManager.adapter?.isOffloadedScanBatchingSupported}")
```

**Comment by stephandue** [comment]
Hi Pawel,
I do have the .withScannerInForegroundService(notification) option. I´ll try the code and paste the log in a minute..
Stephan

**Comment by stephandue** [comment]
![screenshot_pawel](https://user-images.githubusercontent.com/17729818/34292695-1b96272c-e702-11e7-9df1-f86c57f61446.jpg)

**Comment by pawelDylag** [comment]
You need to add import for `BluetoothManager`.

**Comment by stephandue** [comment]
Just did that .. also needed to increase minSdkVersion from 19 to 21 (i´m using your demo project). 

Here´s the log´s output:
12-22 10:50:10.565 8505-8505/com.estimote.proximityapp D/BLUETOOTH CHECK: Is offloaded filtering supported: true
12-22 10:50:10.566 8505-8505/com.estimote.proximityapp D/BLUETOOTH CHECK: Is offloaded scan batching supported: false

**Comment by pawelDylag** [comment]
Ok, so we need to make sure that the system is not calling `onDestroy()` when your screen is off - just to make sure, add this to your `onDestroy()` code and tell me if it's called when you turn the screen off: 
```Kotlin
  override fun onDestroy() {
        super.onDestroy()
        Log.d("BLUETOOTH CHECK", "ON DESTROY")
        proximityObservationHandler.stop()
    }

**Comment by stephandue** [comment]
Hi Pawel,

I already removed
proximityObservationHandler.stop()

Before my test.
Best
Stephan

**Comment by stephandue** [comment]
onDestroy()
is not getting called when the screen goes off. Just tested it.

**Comment by stephandue** [comment]
Is there any update on this?

**Comment by stephandue** [comment]
Hi Pawel, any progress here? Thanks Stephan

**Comment by pawelDylag** [comment]
Hey @stephandue, 

We are waiting for Huawei P10 to arrive at our office. We will test the BLE scanning on it and will let you know about the results. 

Regards, 
Paweł

**Comment by pawelDylag** [comment]
Hello everyone, 

It's a little bit late, but anyway: 

Some Huawei phones have `battery optimizers` turned on as a default for each app. In the result, the scan is stopped whenever the phone's screen goes off. You can turn it off manually for your app, here is a tutorial I find helpful: 

http://nine-faq.9folders.com/articles/16876-how-to-turn-off-battery-optimization-on-the-huawei-devices

Also, there is a possibility to turn it off programaticaly like this: 

``` Kotlin
try {
  val intent = Intent(android.provider.Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS)
  intent.data = Uri.parse("package:$packageName")
  startActivity(intent)
} catch (e : ActivityNotFoundException) {
   e.printStackTrace()
}
```
And add to your manifest.xml:
``` XML
<uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
```
Disabling this should fix onExit events being called when screen goes off.

Regards, 
Paweł
